# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ffbd60d5718d84eaa5cbdf1ffff0554030678bfcba13c374fa6a323fbf685abe5d8ff280a5e8709d4ce6b85b1304589aa32a5fdfa73b950c40471bd57dd1ba

test:
  secret_key_base: c1944c7a23a371a46ea04628f8b4fc640741cff8b47d281443d01d147dd774d8125032fdfb079966822e925894db6ff4054b24ebcd0046259cff1e38ff77b12b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
